# Generated by Django 3.2.5 on 2021-07-12 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='end',
            new_name='endp',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='start',
            new_name='startp',
        ),
    ]
