# Generated by Django 3.2.5 on 2021-07-13 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20210713_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='date',
        ),
    ]
