# Generated by Django 3.2.5 on 2021-07-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_travel_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
